### ISSUE TITLE
Update formatting rules

### ISSUE THREAD

**Issue by weiland** [swrlab/eslint-plugin-swr#136]
https://eslint.org/blog/2023/10/deprecating-formatting-rules/

ESLint's formatting rules will be deprecated.

If not covered by prettier, one could consider moving the *formatting* rules to [`eslint-stylistic`](https://github.com/eslint-stylistic/eslint-stylistic)

**Comment by frytg** [comment]
I assume this will now be tracked in or be part of https://github.com/swrlab/style-guide/issues/2
